### ISSUE TITLE
mesh generator

### ISSUE THREAD

**Issue by wangyf** [cjvogl/finite_volume_seismic_model#1]
Hi:

I read your recent paper and happened to find you have a github account maintaining it. That's cool. Because I use generalized finite difference to simulate earthquake dynamics and our mesh is very alike your generated but much advanced than ours, could you aid us about your meshing strategies (cause there is some in your paper) or point out which subroutine in your package implemented this function. Thanks a lot.

Yongfei

**Comment by cjvogl** [comment]
Hi Yongfei,


Thanks for taking an interest in our paper and related code.  The mapping can be found in two different places: in  [mapc2p.f90](https://github.com/cjvogl/finite_volume_seismic_model/blob/master/2d/mapc2p.f90) (used in the simulations) and [mapping.py](https://github.com/cjvogl/finite_volume_seismic_model/blob/master/2d/mapping.py) (used in the plotting).  If further elaboration would be useful, just let me know.


Cheers!
